Toblerity/rtree

- README.md
It seems like pretty common practice to link to the actual builds, and is nice to have.
> Fix build status link to point to Travis CI

- .travis.yml
- rtree/index.py
- tests/test_index.py
- tests/test_pickle.py
Make Index and Property objects pickleable. This fixes issue #42 .
Also, move ctypes handle objects into their own wrapper objects. The lifetime of the underlying C object is tied to the wrapper. This makes it easier to pass handles without worrying about ownership.
> Add pickling support (fixes #42)

- MANIFEST.in
- rtree/core.py
- rtree/index.py
- scripts/visualize.py
- setup.py
- tests/benchmarks.py
- tests/data.py
- tests/test_doctests.py
- tests/test_index.py
- tests/test_pickle.py
This patch changes the Rtree code style to adapt to the [PEP 8 Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/). There should be no functional changes, except for correction to MANIFEST.in, and making setup.py an executable. A few unused imports are also removed, and the print statement in visualize.py is updated for Python 3 (although not tested).
> Apply formatting for PEP 8 code style

- rtree/core.py
- setup.py
The SPATIALINDEX_C_LIBRARY and SPATIALINDEX_LIBRARY can be used to
specify non standard location and name (OSGeo4W64 has a spatialindex_c-64.dll)
This should address #56 and #64 
Tested on ubuntu 15.10 and windows 7.
> added env variables to find spatialindex_c

- MANIFEST.in
The `CREDITS.txt` file is not included in the tarballs on PyPI.
> Include all text files in sdist

- .travis.yml
The whitelist for the required package has finally been accepted, cf. travis-ci/apt-package-whitelist#4194.
> Switch to container-based Travis builds.

- tests/test_index.py
Skip when not avilable in version of libspatialindex
> Add skip for Index result offset and limit tests

- docs/source/changes.txt
I was looking at the changes for the last release (https://rtree.readthedocs.io/en/latest/changes.html#id2), and this fixes the rst formatting (rst needs a blank line around lists)
> DOC: fix rst formatting in changes.txt

- .travis.yml
- README.md
- ci/azp/conda.yml
- ci/azp/docker.yml
- ci/azp/linux-1604-pip.yml
- ci/azp/linux-1804-pip.yml
- ci/azp/osx.yml
- ci/azp/win.yml
- rtree/core.py
- rtree/index.py
Flake8 linting of core modules (`rtree/index.py` and `rtree/core.py`, ignoring E501)
> Flake8 linting of core modules (`rtree/index.py` and `rtree/core.py`, ignoring E501)

- rtree/index.py
* Add `get_size` method for `rtree.index.Index` and `rtree.index.RtreeContainer`, which returns a count of the number of index objects/entries
* Add custom `__repr__` for both these classes that displays the current index bounds and the size count when the object is printed out to the console
> Add index size and custom `__repr__` methods for index classes

- rtree/__init__.py
- setup.py
If you try to `pip install rtree` without `libspatialindex` the pip install fails, because `setup.py` imports `rtree`. If you didn't have this, `libspatialindex` could be installed later without killing the pip install. PR'ing as I ran into https://github.com/Toblerity/rtree/issues/135 as well and this prevents the error on install. 
Setup only needs rtree to set the version, this changes it to get that version directly from `__init__.py`. This also changes whitespace in `setup.py` to match pep8.
> Don't import rtree in setup.py

- rtree/finder.py
While chasing down a very confusing issue regarding shared libraries on macOS (not my native platform), I came across a small quirk in the way that `rtree` tries to find and load the `spatialindex_c` library. 
On macOS/Linuxc, when it cannot identify the absolute path to `libspatialindex_c.[so,dylib]`, the `rtree.finder` module falls back to using [`ctypes.util.find_library` and `ctypes.cdll.LoadLbirary`](https://github.com/Toblerity/rtree/blob/519856c462040cb29bf1ff9a43faaa48bb2865ab/rtree/finder.py#L113-L117) to find and load the shared library: 
```python
rt = ctypes.cdll.LoadLibrary(
find_library('spatialindex_c'))
if rt is not None:
return rt
```
However (at least on certain versions of macOS/Python), calling `ctypes.cdll.LoadLibrary(None)` actually returns a `CDLL` object, not …
> MNT: Check return value of find_library, not LoadLibrary

- rtree/index.py
`Index.get_coordinate_pointers(coordinates)` converts point-inputs to bounding boxes. However, it does so using the `+=` operator, which has the unfortunate side effect of mutating list inputs, and breaking with numpy arrays (which sum with `+=` rather than appending). This change switches from `+=` to `=` to prevent input-mutation, and uses `coordinates = *coordinates, *coordinates` for numpy compatibility.  
**Before**
``` Python
In [1]: import numpy as np
...: import rtree
...:
...: boxes15 = np.genfromtxt('boxes_15x15.data')
...: idx = rtree.index.Index()
...: for i, coords in enumerate(boxes15):
...:     idx.add(i, coords)
In [2]: # Tuples work and are not mutated (good)
...: point = 64, 64
...: list(idx.intersection(point))
Out[2]: [4, 53]
In [3]: point
Out[3]: (64, 64)
In [4]: # …
```
> Prevent get_coordinate_pointers from mutating input coordinates

- rtree/index.py
- tests/test_index.py
This PR adds a `__len__` method to `Index`, defining the length of an index as the number of entries in that index. This is analogous to the definition of length for Python sets.
This PR also documents and tests the `get_size` method which provides identical functionality. This method has never been documented before. Should we deprecate or remove it in favor of `__len__`? It's definitely more Pythonic to rely on these kinds of magic methods instead of `get_*` and `set_*` methods.
Closes #194 
@hobu
> Add __len__ method to Index

- .github/workflows/build.yml
- .readthedocs.yaml
- readthedocs.yml
ReadTheDocs has its own CI platform. We should use this instead of GitHub Actions for the following reasons:
* Identical environment as the one where the docs are actually hosted
* Better control over Python version used during testing (#212)
* Able to preview docs for a PR before it is merged
This PR updates `.readthedocs.yaml` to the latest API and sets `fail_on_warning: true` so we can catch documentation issues before a PR is merged. However, to get ReadTheDocs CI set up, someone with admin privileges will need to configure a few additional things. @hobu can you follow the instructions at https://docs.readthedocs.io/en/stable/pull-requests.html and see if that works?
@mwtoews may also be interested in this.
> Test docs using ReadTheDocs CI instead of GitHub Actions

- tests/conftest.py
Running the unit tests with pytest results in the following deprecation warnings:
```
tests/conftest.py:12
/Users/Adam/Downloads/rtree/tests/conftest.py:12: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
Use @pytest.fixture instead; they are the same.
@pytest.yield_fixture(autouse=True)
```
This PR updates the fixture to its modern name.
> pytest: update deprecated fixture

- DEPENDENCIES.txt
- docs/source/install.txt
- environment.yml
- rtree/index.py
> Bump required version of libspatialindex

- pyproject.toml
- setup.cfg
- setup.py
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for more information.
The advantage of this is that we don't have to do anything fancy in `setup.py` to extract the `__version__` or use the `README.txt`. This was causing flake8 to complain since `__version__` was undefined.
> Use setuptools' declarative config

- .github/workflows/build.yml
- docs/source/conf.py
- pyproject.toml
- rtree/__init__.py
- rtree/core.py
- rtree/exceptions.py
- rtree/finder.py
- rtree/index.py
- scripts/visualize.py
- setup.py
- tests/conftest.py
- tests/test_index.py
- tests/test_tpr.py
This PR uses `black` and `isort` to auto-format the repo. These tools are developed by PSF and PyCQA and used by many projects to enforce a common PEP-8 compliant standard. Unlike `flake8`, these tools are auto-formatters, so if someone submits a PR that doesn't pass these tests, they simply need to run `black .` or `isort .` in the repo and it will solve all of their issues. This was incredibly useful when working on #215 since the type hints I added increased the line length of most function signatures above the 88 character limit. Downside is that `git blame` is much less useful now since this PR affects most files. But the same will be true with #215 since it edits every function signature.
> Blacken repo

- docs/source/conf.py
This list was modified in #219, resulting in the need for type hints. But #215 was merged at the same time, before type hints were required. Now that both PRs have been merged, the mypy tests are failing without this.
> Mypy: fix type hints for doc list

- docs/source/conf.py
- rtree/core.py
- rtree/finder.py
- rtree/index.py
- scripts/visualize.py
- tests/test_index.py
Modernize the code base to Python 3.7+ using [pyupgrade](https://github.com/asottile/pyupgrade) with a few manual modifications for string formatting. Also change a message with "LASError" (from libLAS) to simply "Error".
The initial command was:
```
pyupgrade --py37-plus --keep-runtime-typing `find . -name "*.py"`
```
> Apply pyupgrade --py37-plus --keep-runtime-typing, with mods

- rtree/core.py
This fixes #220 by correcting the mismatches with the `libspatialindex` API that were noted in that issue and its comments.
> Fix C API mismatches vs. libspatialindex

- tests/test_index.py
This also restores one test that was always skipped.
Xref https://github.com/Toblerity/rtree/pull/225#issuecomment-1049295432
> Remove Python 2 conditional testing

- tests/test_index.py
Not sure what the underling issue is yet, but this part can be skipped for 32-bit Python.
Xref #228
> Skip part of test_interleaving for 32-bit systems

- rtree/index.py
- tests/test_index.py
Still a work in progress. I was planning on taking the intersection of two Item objects but the Item constructor doesn't seem to contain bounds so it's unclear how to do this. Also, things might be different depending on interleave=True/False. Will definitely need extensive testing.
Closes #209
> Index/Item: add intersection/union support

- tests/test_index.py
This PR adds the tests from #197 so we can at least properly test index pickling. This test is marked as xfail since rtree indices currently can't be pickled without losing all contents. Hopefully this will make it easier to fix and test in the future.
> Add xfail test for pickling

- docs/source/tutorial.txt
I'm not sure when `Index.insert(...)` had "bounds" as a keyword argument, but it seems to be incorrect.
(although I feel like copy+pasting this line from the tutorial page has worked for me in the past at some point; no idea when)
> Update keyword argument in docs

- MANIFEST.in
- setup.cfg
After #215, I was excited to take advantage of type hints in my projects that
use Rtree. However, after upgrading to v1.0.0, mypy was giving [import
errors]. According to those docs, mypy will only infer/lookup types from
installed packages if they are [PEP 561] compliant.
Fortunately, all that seems to [involve] is the inclusion of a `py.typed` marker
file in the installed package. This PR is my attempt at doing just that. In my
local testing, this seems to resolve the above Mypy import warnings.
I'm new to setuptools and distributing sdist wheels though, so I'm not sure how
to confirm this file will be included in the built wheels? From reading the
[setuptools docs], I think this is right, but probably worth review from someone
who knows these things better.
[import errors]: …
> Make Rtree PEP 561-compliant, so that Mypy finds type hints

- .github/workflows/build.yml
A bit of CI maintenance:
- Updates all the used actions (checkout, setup-python, cibuildwheel) to their latest versions.
- Clean up the Ubuntu build matrix and add multiple Python versions
- Adds a weekly scheduled run to all CI workflows, which run each Monday at 06:00 UTC. A periodically scheduled run can detect errors and warnings appearing in changes in upstream dependencies or the build environment. By having a scheduled run they can be traced back easier to a dependency or environment change, then if they would pop up in a random PR.
- Update to libspatialindex-c6 on Ubuntu to support the 20.04 and 22.04 LTS versions
The updated cibuildwheel version will also build Python 3.11 wheels for the next release.
> CI: Update used actions, add weekly schedule

- .github/workflows/build.yml
Only run the CI on pushes to the master branch when the CI configuration is changed. This saves some time, since our CI matrix is huge.
Still also runs on all PRs, releases and once a week.
> CI: Only run on pushes to the master branch or CI change

- .github/workflows/build.yml
Refactor and simplify the wheel building. A single job now builds all `aarch64` wheels, using the [cibuildwheel](https://github.com/pypa/cibuildwheel) GitHub Action (following [these docs](https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation)).
The regular wheels are also build by the GitHub Action.
Another advantage is that Dependabot will update the GitHub Action once a new cibuildwheel version is released.
> CI: Simplify wheel building

- docs/source/conf.py
Today's Sphinx 6.2.0 release deprecated the old style of `intersphinx_mapping`: https://github.com/sphinx-doc/sphinx/pull/11247
This was causing our tests to fail.
> Docs: update intersphinx_mapping to modern style

- rtree/index.py
This PR fixes a memory leak that is caused from resources not being freed when using `_get_objects` and `_get_ids` and not consuming all of the items in the generator.
Explanation - this is the way these functions are implemented currently:
```
>>> def objects():
...   try:
...     for i in range(10):
...       yield i
...     print('release mem 1')
...   except Exception as e:
...     print('release mem 2')
...     raise
```
When iterating the objects, but breaking mid way, the memory is not released:
```
>>> for x in objects():
...   print('got', x)
...   if x == 5: break
... 
got 0
got 1
got 2
got 3
got 4
got 5
>>> 
```
If we use `finally` instead, it simplifies the code and ensures that memory is always released:
```
>>> def objects():
...   try:
...     for i in range(10):
... …
```
> Fix memory leak when breaking mid-way in _get_objects and _get_ids

- .github/workflows/build.yml
- DEPENDENCIES.txt
- environment.yml
- pyproject.toml
- rtree/__init__.py
- rtree/core.py
- rtree/exceptions.py
- rtree/finder.py
- rtree/index.py
- tests/conftest.py
- tests/test_index.py
- tests/test_tpr.py
This PR drops Python 3.7 which reached it's end-of-life in June 2023 ([PEP 537](https://peps.python.org/pep-0537/)).
Testing and some code is modified to assume Python 3.8+. Some of this was automated using `pyupgrade --py38-plus`.
Closes #228
> Drop Python 3.7, upgrade typing for 3.8+

- .github/workflows/build.yml
- .gitignore
- ci/install_libspatialindex.bash
- pyproject.toml
- rtree/finder.py
- scripts/repair_wheel.py
- tox.ini
There are a few aims in this PR:
- Move cibuildwheel data from GitHub Actions variables to pyproject.toml
- Build each platform, but allow to work with any Python 3 version, since this is a Pure Python project
- Use tox to run pytest for all Python versions
- For Linux, remove duplicated `rtree/lib`; close #270
- Modify finder to look for auditwheel-built shared library (using `importlib.metadata.files`)
The repair_wheel.py script was modified from [cmake-python-distributions](https://github.com/scikit-build/cmake-python-distributions/blob/master/scripts/repair_wheel.py). Admittedly, there are several things that I don't understand, but have left alone. It uses `wheel unpack` and `wheel pack` to modify the binary wheels.
> Refactor cibuildwheel setup

- tests/test_index.py
- tests/test_tpr.py
This was mostly automated with pyupgrade. Review appreciated as I'm a typing novice.
Note that these files have `from __future__ import annotations` at the top; xref #273
> Upgrade typing for tests (via pyupgrade)

- rtree/finder.py
The autopkgtest for the Debian package fails:
```
I: pybuild base:291: cd /tmp/autopkgtest-lxc.o4fl70zh/downtmp/autopkgtest_tmp/build; python3.11 -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.4.2, pluggy-1.3.0
rootdir: /tmp/autopkgtest-lxc.o4fl70zh/downtmp/autopkgtest_tmp/build
collected 0 items / 2 errors
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_index.py _____________________
/usr/lib/python3/dist-packages/_pytest/runner.py:341: in from_call
result: Optional[TResult] = func()
/usr/lib/python3/dist-packages/_pytest/runner.py:372: in <lambda>
call = CallInfo.from_call(lambda: list(collector.collect()), …
```
> Fix test failure with built library.

- tests/test_index.py
The Debian package build for rtree failed on i386 due to test failures:
```
I: pybuild base:291: cd /builds/debian-gis-team/python-rtree/debian/output/source_dir/.pybuild/cpython3_3.11_rtree/build; python3.11 -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.4.2, pluggy-1.3.0
rootdir: /builds/debian-gis-team/python-rtree/debian/output/source_dir
collected 38 items
tests/test_index.py ........x............F...............                [ 97%]
tests/test_tpr.py .                                                      [100%]
=================================== FAILURES ===================================
_____________________ IndexSerialization.test_interleaving _____________________
self = …
```
> Skip test failing on i386.

- .pre-commit-config.yaml
- pyproject.toml
- rtree/__init__.py
- rtree/exceptions.py
- rtree/finder.py
- rtree/index.py
- scripts/repair_wheel.py
- tests/test_index.py
- tests/test_tpr.py
Update the Python code style (again!) using ruff lint tools, which replace isort and black. Also select pyupgrade and numpy-specific checks. The Python code changes are mostly style, and should not have any functional changes.
The updated pre-commit hooks are also integrated with pre-commit.ci
> Update code style, replace isort and black with ruff, modern numpy rng

- CHANGES.rst
- CREDITS.txt
- docs/source/performance.rst
- rtree/__init__.py
> Release 1.3.0

- .github/workflows/test.yml
- DEPENDENCIES.txt
- environment.yml
- pyproject.toml
- rtree/index.py
- tests/conftest.py
- tests/test_index.py
- tests/test_tpr.py
- tox.ini
With 1.3.0 freshly released this seems like a good moment to drop Python 3.8 support. It's almost [end-of-life](https://endoflife.date/python) and [SPEC 0](https://scientific-python.org/specs/spec-0000/) already recommended dropping Python 3.8 over a year ago.
In fact, they even recommend already dropping Python 3.9 and requiring 3.10+, which many packages do. But that might be a bit much for one PR.
So this PR bumps the required Python version to 3.9, removes 3.8 from the CI and test files and applies [pyupgrade](https://github.com/asottile/pyupgrade) with `--py39-plus`.
Of course this will only affect future releases, existing releases stay compatible with Python 3.8 and can continued to be used.
> Drop Python 3.8 support, require Python 3.9+

- .github/workflows/test.yml
Python 3.13 is now in beta, thus is might be useful to start testing what works and what doesn't.
This PR adds a Python 3.13 jobs for the conda and regular Ubuntu pip jobs.
It also fixes a bug in the Ubuntu job, by making sure the Python version specified in the matrix is actually used when setting up Python.
> CI: Add test job for Python 3.13

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Notes on the changes:
- Tests will fail from warnings (`-Werror`)
- Use verbose messages with pytest, since this is the primary output to review
- Change `fail-fast: false` to run all jobs of a matrix, even if there is one failure
- Remove the pre-commit workflow job, since pre-commit.ci was recently configured
- Use conda to install pytest for the conda jobs (not pip)
- Apt should't install python3-pip, and use `apt-get` for non-interactive use
- Remove 'paths' for 'push', so that the tests are re-run after pull-requests are merged to master
> CI: fail with warnings, and several minor tunings to test workflow

- .readthedocs.yaml
Use latest Ubuntu and Python versions for Readthedocs. These are faster and throw more detailed errors if anything goes wrong.
> Update .readthedocs.yaml: Use latest Ubuntu and Python versions

- pyproject.toml
- tox.ini
CI testing is already done with Python 3.13, but the classifier and tox environment needed to be updated.
> MAINT: add Python 3.13 classifier and tox env

- rtree/index.py
This PR aims to reduce API overhead.  For small in-memory trees the benefits can be substantial (30% or more).  General ideas:
- Function calls with ctypes are expensive (1µs per call).  So, we add caching to the tree type and index dimension properties.  This greatly cuts down on the number of times we need to call into the library.
- The bulk loading routine calls `deinterleave` which is slow and does a lot of ctypes casting.  This replaces it with slice assignment which is more direct and faster (for my test case tree construction goes from ~10s to ~7s).
- We also adopt slice assignment for `get_coordinate_pointers`.  There should now be virtually no overhead from not interleaving.  Moreover, point arguments should be a bit faster as we avoid some work by returning the same pointer …
> Reduce overhead.

- rtree/core.py
- rtree/index.py
This is the counterpart to https://github.com/libspatialindex/libspatialindex/pull/267
> Add support for array-based bulk insert

- tests/test_index.py
Fixes a few bugs discovered in #344. Separated them out into their own PR to make them easier to review/merge.
> rtree.index: fix test bugs

- .gitignore
- pyproject.toml
- rtree/finder.py
- scripts/repair_wheel.py
This renames the project name from "Rtree" to "rtree", which resolves tools that assume lowercase names.  Just looking at the build tools like setuptools and cibuildwheel, I'm noticing that they are less forgiving for projects with mixed-case project names.
For example, I've looked over the PyPI archives, up to [version 0.8.3](https://pypi.org/project/Rtree/0.8.3/#files) (Dec 15, 2016) the sdist and bdist files are consistently `Rtree*`. However, since [version 0.9.1](https://pypi.org/project/Rtree/0.9.1/#files) (Nov 26, 2019) the files are either `Rtree-*.tar.gz` sdist or `rtree-*.whl` bdist files. And now recent cibuildwheel and/or auditwheel tools assume lowercase projects, and don't work anymore (#349).
This change would make sdist and bdist files (e.g. for PyPI) consistently …
> Rename project to lowercase "rtree"

- .github/workflows/deploy.yml
- pyproject.toml
Details of this image are [here](https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-24-image.md). It should make building and testing Linux ARM wheels much quicker.
> CI: use ubuntu-24.04-arm instead of QEMU to build ARM-based wheels

- .pre-commit-config.yaml
- benchmarks/benchmarks.py
This update really only has one change from `ruff format` with an improvement in `benchmarks/benchmarks.py`.
> Update pre-commit hook versions

- .github/workflows/test.yml
- scripts/install_libspatialindex.bat
- scripts/install_libspatialindex.sh
This updates wheel building and testing to use [libspatialindex-2.1.0](https://github.com/libspatialindex/libspatialindex/releases/tag/2.1.0).
> Update testing to libspatialindex-2.1.0

- CHANGES.rst
- README.md
- docs/source/class.rst
- docs/source/install.rst
- rtree/__init__.py
- setup.py
- tests/conftest.py
This contains release notes for v1.4.0. It also has a "last minute" update to the pytest report header to show the version of NumPy and libspatialindex.
Closes #348
> Release 1.4.0

- rtree/index.py
The existing implementation confuses `numpy.resize` that returns a new resized array, with `numpy.ndarray.resize` that resizes the array in-place and returns None. Relevant numpy documentation:
https://numpy.org/doc/stable/reference/generated/numpy.resize.html
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html
This causes calls to nearest_v and intersection_v to fail in cases where `nr.value == n - offn` evaluates to false.
> Fixing an incorrect reassignment in nearest_v and intersection_v

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- pyproject.toml
- tests/common.py
- tests/conftest.py
- tox.ini
This adds a `common` module for the tests, for items that aren't fixtures. So far it gets the libspatialindex version string and tuple.
Also establish a pytest configuration.
> Add spatialindex version to tests, add common pytest configuration

- rtree/index.py
- tests/common.py
- tests/test_index.py
This refactors the newly added [`intersection_v`](https://rtree.readthedocs.io/en/latest/class.html#rtree.index.Index.intersection_v) and [`nearest_v`](https://rtree.readthedocs.io/en/latest/class.html#rtree.index.Index.nearest_v) functions, and adds some tests.
- Allow functions to take lists as inputs, using NumPy's [`atleast_1d`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_1d.html) and [`atleast_2d`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html) functions to sanitise inputs for ctypes
- Replace `assert` checks with more verbose checks that raise ValueError, checking dimensions, shape and strides
- Change the function signature of `nearest_v` to enforce keyword-only from `num_results`; this function is new, so I don't anticipate this change …
> Refactor array-loading methods, add tests

- .github/workflows/test.yml
- docs/source/install.rst
- docs/source/performance.rst
- docs/source/tutorial.rst
This is a relatively minor refactor of the code blocks in the docs. Mostly to update the look-and-feel via blacken-docs (not added as a check or pre-commit), but also to check that they are running as expected, now checked in unit tests.
There were some Python 2 left-overs updated for Python 3. Also, temporary directories are used for the disk serialization examples, so they don't pollute the current working directories (and these tests break when run more than once due to the append mode).
> Minor refactor of code blocks in docs
